title : Introduction to Data Science
author: Jun Yan and students in STAT 5255, Fall 2021
logo: 'tricircle.pdf'

# Short description about the book
description: >-
  A collection of notes for jump starting in data science with Python.

execute:
  execute_notebooks           : cache

# HTML-specific settings
html:
  home_page_in_navbar         : false

# Interact link settings
notebook_interface            : "notebook"

# Launch button settings
repository:
  url                         : https://github.com/jun-yan/ids
  path_to_book                : "notes"

binder:
  binderhub_url               : "https://mybinder.org"
  text                        : "Launch binder"

# LaTeX settings
bibtex_bibfiles:
   - _bibliography/references.bib
latex:
  latex_engine                : "xelatex"
  latex_documents:
    targetname: book.tex
